version: "3"

services:
  datzproject:
    # environment:
    #   - DISPLAY=host.docker.internal:0
    image: mkdatz/datzprojectflask
    ports: 
      - 5000:5000
    container_name: datzproject

  rstudio-server:
    environment:
      - DISABLE_AUTH=true
    image: rocker/rstudio
    ports:
      - 8787:8787
    container_name: rstudio-server

  spyder:
    environment:
      - DISPLAY
    image: compdatasci/spyder-desktop
    ports:
      - 6080:6080
    container_name: spyder

  gitea:
    image: gitea/gitea:1.12.4
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db
    restart: always
    environment: 
      - DISABLE_REGISTRATION=true
    container_name: gitea

  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=changeme
    volumes:
      - ./db/:/var/lib/mysql
    container_name: db

  jupyter:
    image: jupyter/minimal-notebook
    environment:
      - JUPYTER_TOKEN=easy
    ports:
      - 8889:8889
    container_name: jupyter
    command: jupyter notebook --allow-root --ip='0.0.0.0' --port=8889 --no-browser --NotebookApp.token='' --NotebookApp.password=''
  
  orange:
    environment:
      - DISPLAY
    image: acopar/orange-docker
    ports:
      - 5901:5901 
      - 6901:6901
    tty: true
    container_name: orange
    environment:
      - VNC_PW=pass
  
  vscode:
    environment:
      - DISPLAY
    image: linuxserver/code-server
    ports:
      - 8443:8443
    container_name: vscode

  # tableau:
  #   environment:
  #     - DISPLAY
  #   image: pvtmert/tableau
  #   ports:
  #     - 8316:8316
  #     - 8731:8731
  #     - 8850:8850
  #   container_name: tableau

  # sonarqube:
  #   container_name: sonarqube
  #   ports:
  #     - 9000:9000
  #   restart: on-failure
  #   user: "999"
  #   image: sonarqube

  tensorflow:
    image: jupyter/tensorflow-notebook
    ports:
        - 8888:8888
    container_name: tensorflow
    command: jupyter notebook --allow-root --ip='0.0.0.0' --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password=''

  # MARKDOWN SERVER ALL GOOD
  markdown-server:
    image: v4tech/markdown-editor
    ports:
      - 12345:80
    container_name: markdown-server

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - CORE_CONF_io_compression_codecs=org.apache.hadoop.io.compress.SnappyCodec

      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false

      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
      - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
      - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
      - YARN_CONF_yarn_resourcemanager_scheduler_class=org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
      - YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___mb=8192
      - YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___vcores=4
      - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
      - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
      - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
      - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
      - YARN_CONF_yarn_timeline___service_enabled=true
      - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
      - YARN_CONF_yarn_timeline___service_hostname=historyserver
      - YARN_CONF_mapreduce_map_output_compress=true
      - YARN_CONF_mapred_map_output_compress_codec=org.apache.hadoop.io.compress.SnappyCodec
      - YARN_CONF_yarn_nodemanager_resource_memory___mb=16384
      - YARN_CONF_yarn_nodemanager_resource_cpu___vcores=8
      - YARN_CONF_yarn_nodemanager_disk___health___checker_max___disk___utilization___per___disk___percentage=98.5
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - YARN_CONF_yarn_nodemanager_aux___services=mapreduce_shuffle

      - MAPRED_CONF_mapreduce_framework_name=yarn
      - MAPRED_CONF_mapred_child_java_opts=-Xmx4096m
      - MAPRED_CONF_mapreduce_map_memory_mb=4096
      - MAPRED_CONF_mapreduce_reduce_memory_mb=8192
      - MAPRED_CONF_mapreduce_map_java_opts=-Xmx3072m
      - MAPRED_CONF_mapreduce_reduce_java_opts=-Xmx6144m
      - MAPRED_CONF_yarn_app_mapreduce_am_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
      - MAPRED_CONF_mapreduce_map_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
      - MAPRED_CONF_mapreduce_reduce_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      # SERVICE_PRECONDITION: "namenode:9870"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - CORE_CONF_io_compression_codecs=org.apache.hadoop.io.compress.SnappyCodec

      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false

      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
      - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
      - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
      - YARN_CONF_yarn_resourcemanager_scheduler_class=org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
      - YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___mb=8192
      - YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___vcores=4
      - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
      - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
      - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
      - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
      - YARN_CONF_yarn_timeline___service_enabled=true
      - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
      - YARN_CONF_yarn_timeline___service_hostname=historyserver
      - YARN_CONF_mapreduce_map_output_compress=true
      - YARN_CONF_mapred_map_output_compress_codec=org.apache.hadoop.io.compress.SnappyCodec
      - YARN_CONF_yarn_nodemanager_resource_memory___mb=16384
      - YARN_CONF_yarn_nodemanager_resource_cpu___vcores=8
      - YARN_CONF_yarn_nodemanager_disk___health___checker_max___disk___utilization___per___disk___percentage=98.5
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - YARN_CONF_yarn_nodemanager_aux___services=mapreduce_shuffle

      - MAPRED_CONF_mapreduce_framework_name=yarn
      - MAPRED_CONF_mapred_child_java_opts=-Xmx4096m
      - MAPRED_CONF_mapreduce_map_memory_mb=4096
      - MAPRED_CONF_mapreduce_reduce_memory_mb=8192
      - MAPRED_CONF_mapreduce_map_java_opts=-Xmx3072m
      - MAPRED_CONF_mapreduce_reduce_java_opts=-Xmx6144m
      - MAPRED_CONF_yarn_app_mapreduce_am_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
      - MAPRED_CONF_mapreduce_map_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
      - MAPRED_CONF_mapreduce_reduce_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      # SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - CORE_CONF_io_compression_codecs=org.apache.hadoop.io.compress.SnappyCodec

      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false

      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
      - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
      - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
      - YARN_CONF_yarn_resourcemanager_scheduler_class=org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
      - YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___mb=8192
      - YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___vcores=4
      - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
      - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
      - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
      - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
      - YARN_CONF_yarn_timeline___service_enabled=true
      - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
      - YARN_CONF_yarn_timeline___service_hostname=historyserver
      - YARN_CONF_mapreduce_map_output_compress=true
      - YARN_CONF_mapred_map_output_compress_codec=org.apache.hadoop.io.compress.SnappyCodec
      - YARN_CONF_yarn_nodemanager_resource_memory___mb=16384
      - YARN_CONF_yarn_nodemanager_resource_cpu___vcores=8
      - YARN_CONF_yarn_nodemanager_disk___health___checker_max___disk___utilization___per___disk___percentage=98.5
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - YARN_CONF_yarn_nodemanager_aux___services=mapreduce_shuffle

      - MAPRED_CONF_mapreduce_framework_name=yarn
      - MAPRED_CONF_mapred_child_java_opts=-Xmx4096m
      - MAPRED_CONF_mapreduce_map_memory_mb=4096
      - MAPRED_CONF_mapreduce_reduce_memory_mb=8192
      - MAPRED_CONF_mapreduce_map_java_opts=-Xmx3072m
      - MAPRED_CONF_mapreduce_reduce_java_opts=-Xmx6144m
      - MAPRED_CONF_yarn_app_mapreduce_am_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
      - MAPRED_CONF_mapreduce_map_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
      - MAPRED_CONF_mapreduce_reduce_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      # SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - CORE_CONF_io_compression_codecs=org.apache.hadoop.io.compress.SnappyCodec

      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false

      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
      - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
      - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
      - YARN_CONF_yarn_resourcemanager_scheduler_class=org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
      - YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___mb=8192
      - YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___vcores=4
      - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
      - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
      - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
      - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
      - YARN_CONF_yarn_timeline___service_enabled=true
      - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
      - YARN_CONF_yarn_timeline___service_hostname=historyserver
      - YARN_CONF_mapreduce_map_output_compress=true
      - YARN_CONF_mapred_map_output_compress_codec=org.apache.hadoop.io.compress.SnappyCodec
      - YARN_CONF_yarn_nodemanager_resource_memory___mb=16384
      - YARN_CONF_yarn_nodemanager_resource_cpu___vcores=8
      - YARN_CONF_yarn_nodemanager_disk___health___checker_max___disk___utilization___per___disk___percentage=98.5
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - YARN_CONF_yarn_nodemanager_aux___services=mapreduce_shuffle

      - MAPRED_CONF_mapreduce_framework_name=yarn
      - MAPRED_CONF_mapred_child_java_opts=-Xmx4096m
      - MAPRED_CONF_mapreduce_map_memory_mb=4096
      - MAPRED_CONF_mapreduce_reduce_memory_mb=8192
      - MAPRED_CONF_mapreduce_map_java_opts=-Xmx3072m
      - MAPRED_CONF_mapreduce_reduce_java_opts=-Xmx6144m
      - MAPRED_CONF_yarn_app_mapreduce_am_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
      - MAPRED_CONF_mapreduce_map_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
      - MAPRED_CONF_mapreduce_reduce_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      # SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - CORE_CONF_io_compression_codecs=org.apache.hadoop.io.compress.SnappyCodec

      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false

      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
      - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
      - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
      - YARN_CONF_yarn_resourcemanager_scheduler_class=org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
      - YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___mb=8192
      - YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___vcores=4
      - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
      - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
      - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
      - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
      - YARN_CONF_yarn_timeline___service_enabled=true
      - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
      - YARN_CONF_yarn_timeline___service_hostname=historyserver
      - YARN_CONF_mapreduce_map_output_compress=true
      - YARN_CONF_mapred_map_output_compress_codec=org.apache.hadoop.io.compress.SnappyCodec
      - YARN_CONF_yarn_nodemanager_resource_memory___mb=16384
      - YARN_CONF_yarn_nodemanager_resource_cpu___vcores=8
      - YARN_CONF_yarn_nodemanager_disk___health___checker_max___disk___utilization___per___disk___percentage=98.5
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - YARN_CONF_yarn_nodemanager_aux___services=mapreduce_shuffle

      - MAPRED_CONF_mapreduce_framework_name=yarn
      - MAPRED_CONF_mapred_child_java_opts=-Xmx4096m
      - MAPRED_CONF_mapreduce_map_memory_mb=4096
      - MAPRED_CONF_mapreduce_reduce_memory_mb=8192
      - MAPRED_CONF_mapreduce_map_java_opts=-Xmx3072m
      - MAPRED_CONF_mapreduce_reduce_java_opts=-Xmx6144m
      - MAPRED_CONF_yarn_app_mapreduce_am_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
      - MAPRED_CONF_mapreduce_map_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
      - MAPRED_CONF_mapreduce_reduce_env=HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline

  spark:
    image: jupyter/all-spark-notebook
    container_name: spark
    ports:
      - "8080:8080"
    command: jupyter notebook --allow-root --ip='0.0.0.0' --port=8080 --no-browser --NotebookApp.token='' --NotebookApp.password=''

  # sonarqube:
  #   container_name: sonarqube
  #   ports:
  #       - '9001:9000'
  #       - '9092:9092'
  #   image: sonarqube

# volumes:
#   hadoop_namenode:
#   hadoop_datanode:
#   hadoop_historyserver:
  tableau:
    container_name: tableau
    image: dimtoolsinc/tableau-server:2018-2-3
    volumes:
      - run:/run
      - /sys/fs/cgroup:/sys/fs/cgroup    
    restart: always
    ports:
    - 80:80
    - 8850:8850
    privileged: true

volumes:
  run:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
